### ISSUE TITLE
numExpr / multi-gene problem

### ISSUE THREAD

**Issue by vonGameTheory** [fnoorian/gramEvol#8]
Either I'm missing how it is supposed to work, or multi-expressions don't seem to work.  

Specifically, if I set numExpr = 2, it sends 2 expressions to the cost function only about half the time, but often only 1.

**Comment by vonGameTheory** [comment]
Or looks like it may be a more generalized problem.  Even if numExpr is set to 1, it only calls the cost function about half the time -- other members of the population are being automatically eval'd to Inf without even calling the cost/evaluation function at all (all $evaluations set to Inf).  I even had a first generation run where it didn't call the cost function at all and went straight to the second generation.  

So it is generating a lot of invalid expressions or there is some bug where it isn't sending them to the cost function?

**Comment by fnoorian** [comment]
This was by design. When a chromosome is constructed, there is a high possibility that it is invalid (i.e. not terminal) specially if the grammar has a lot of recursion. So I added some code to avoid passing these invalid expressions to the fitness functions.

I'm not sure if passing incomplete expressions to the fitness function has any value. If it does, let me know!

But to reduce the amount of non-terminal expressions, you can:
* set `seqLen` parameter in `GrammaticalEvolution` to a large number, an/or,
* increase `wrappings` parameter in `GrammaticalEvolution`

**Comment by vonGameTheory** [comment]
At first I figured it was the seqLen and/or wrappings, but I tried setting them to (what I thought would be) absurdly high values (without increasing the depth) and it didn't seem to make much if any difference (except making it go much slower).  I've got a pretty simple grammar, but it does allow recursion.

So I can quibble with a couple of things about that set-up.  

A) In the case of multi-expressions, if you are using the expressions "together" in the evaluation function, then if it doesn't send the full number you ask for, then you can't evaluate the ones that it does send (so that has to go back as Inf also).  That's a side question, actually, the cost function still only returns one overall fitness/cost value even with multi-expressions, right?  Meaning the expressions are separate but they go together.  (And so again, if you don't send them all, that's automatically invalid also.)

B) This just seems like a waste of a generation where only half the individuals or less are valid -- seems like it knows an expression is invalid, it should just randomly (or by some scheme) make another one until it had one that can be evaluated.  (Like I said, I had examples where it just didn't do the first generation at all.)  I guess the other answer is just to double or triple the popSize?  Or I could re-jigger the grammar so it was not officially recursive by creating multiple copies of rules/functions with different names so they could only be used in a certain order or depth.  Or something, have to think about that.

C) If there *was* a bug in there that was (improperly) generating invalid expressions with certain grammars, or flagging valid expressions as invalid, then it would probably go unnoticed/unfound because invalid expressions are "normal".

**Comment by fnoorian** [comment]
A) Yes. The goal was to have multiple expression that do something together. For example, generate features for right hand side of a linear regression.

B) I agree. It might be good to implement this "make sure all expressions are valid" generator. 

C) True. This can specially happen if someone is using string based grammar (rather than native R `grule` which has some syntax checking in it). I wonder if solution to 'B' will help.

Anyway, all pull requests are welcome.

**Comment by vonGameTheory** [comment]
I did re-jigger my grammar so it was not recursive, just made it tiered with a max number of levels and the bottom level only has terminals.  So now I have no problems on that front anyway.
